- name: ensure apache is the latest version
  apk:
    name: apache2
    state: latest

- name: write the apache ports.conf config file
  template:
    src: templates/ports.conf.j2
    dest: /etc/apache2/conf.d/ports.conf
  notify:
    - restart apache2

# - name: Append Include /etc/apache2/ports.conf to httpd.conf
#   lineinfile:
#     path: /etc/apache2/httpd.conf
#     line: "Include /etc/apache2/ports.conf"
#     state: absent
#   notify:
#    - restart apache2
   
- name: write the apache2 index file
  template:
    src: templates/index.html.j2
    dest: /var/www/localhost/htdocs/index.html
  notify:
    - restart apache2

- name: ensure apache2 is running 
  service:
      name: apache2
      state: started